# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Muito obrigado por abrir seu primeiro "issue" aqui!ğŸš€ Certifique-se, na publicaÃ§Ã£o, de ter seguido o template.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Obrigado por abrir esta solicitaÃ§Ã£o de PR!ğŸ’¡ Verifique nossas diretrizes de contribuiÃ§Ã£o.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  ParabÃ©ns pelo _merge_ de sua primeira solicitaÃ§Ã£o de PR! ğŸŠ

# It is recommended to include as many gifs and emojis as possible!
